### ISSUE TITLE
Same subscription for same market

### ISSUE THREAD

**Issue by frodoe7** [altangent/ccxws#111]
It's a question more than a bug
I have this market
```
const market = {
  id: "BTCUSDT", // remote_id used by the exchange
  base: "BTC", // standardized base symbol for Bitcoin
  quote: "USDT", // standardized quote symbol for Tether
};
```

what'll happen if I called these 3 lines
```
binance.subscribeTickers(market);
binance.subscribeTickers(market);
binance.subscribeTickers(market);
```

1 - I'll have 3 connected socket streams
or 2 - the package will internally handle these duplicates and consider only 1 subscription

**Comment by bmancini55** [comment]
Thanks for asking. Calls to the `subscribe*` methods are idempotent, so there will only one subscription.  The package internally manages the subscriptions and ignores duplicates.

**Comment by frodoe7** [comment]
@bmancini55 thanks for your reply and for this useful package
