### ISSUE TITLE
Could your release KuCoin bugfixes? :)

### ISSUE THREAD

**Issue by stakost** [altangent/ccxws#112]
In the last release, you did not add fixes KuCoin.

Could you add it please? :)

**Comment by bmancini55** [comment]
Now released, sorry about that. 
https://github.com/altangent/ccxws/releases/tag/v0.29.1

**Comment by stakost** [comment]
Thanks!
And could you remove console.log form kucoin-client? :)

**Comment by bmancini55** [comment]
Released in https://github.com/altangent/ccxws/releases/tag/v0.29.3
