### ISSUE TITLE
Will you add reconnect for Poloniex?

### ISSUE THREAD

**Issue by stakost** [altangent/ccxws#113]
Sometimes Poloniex fails and does not send any messages :(

**Comment by bmancini55** [comment]
Poloniex already has a connection watcher that automatically reconnects.

Can you provide any additional information that would help us troubleshoot?

**Comment by stakost** [comment]
Yes, I see that there are reconnection methods in the poloniex-client (inherits methods). but in my practice the restart of the web socket never happened.
I wrote on top of your controller a method that delayed reconnect. in this case it works.

**Comment by bmancini55** [comment]
Do you have any logging you could share and do you mind sharing the change you've made that fixes it for you?  

We haven't experienced this issue with our system so its hard to know exactly what needs to change without more info.  FWIW, we have 5 processes collecting information from Poloniex which have reconnected quite a lot without incident. 

Thanks

**Comment by athenawisdoms** [comment]
@bmancini55 Whats behind the decision to use 5 processes to collect data a single exchange? Is Poloniex disconnecting the Websocket clients so frequently that more than 2 processes are needed to avoid missing data?

**Comment by bmancini55** [comment]
Redundant feeds split by type (trades and order books).  This allows for zero-downtime software upgrades and server maintenance.
