### ISSUE TITLE
Gemini ticker support

### ISSUE THREAD

**Issue by evan-coygo** [altangent/ccxws#114]
**Exchange**
Gemini
**Subscription type**
Ticker

Gemini implementation doesn't support ticker updates right now. Although the API doesn't officially support a ticker subscription, we may be able to achieve it by listening to trade activity. I haven't done a deep dive of the Gemini docs yet but I wanted to get this issue here to track it. There is an API for candlestick data, and an API for public trade events, so I believe it should be possible.

**Comment by evan-coygo** [comment]
Gemini Market Data v1 api supports a "top of book" subscription type which will only include the top ask/bid, which is perfect for ticker data, but this doesn't include a last price.

It looks like to get the last traded price we need to either use a REST API to get that last price, then listen for subsequent trade events, or we can use the Market Data V2 API which includes the last 50 trades w/initial response. This doesn't support a "'top of book" option though so we'd need to do a little more logic to make sure we know the current ask/bid if we don't want to store the entire order book in memory (which should be avoided for a simple ticker).

**Comment by bmancini55** [comment]
This is now released in https://github.com/altangent/ccxws/releases/tag/v0.29.4
Thanks!
