### ISSUE TITLE
Bittrex Base Volume and Quote Volume is wrong

### ISSUE THREAD

**Issue by iamamitshinde** [altangent/ccxws#115]
**Exchange**
Bittrex

**Subscription type**
subscribeTicker

**Describe the bug**
The base volume and quote volume is assigned incorrectly. Bittrex sends quote volume with "BaseVolume" tag, so it should be assigned to the quote volume.

Current assigned code:
`      volume: BaseVolume.toFixed(8),
      quoteVolume: Volume.toFixed(8),`

It should be:

`      volume: Volume.toFixed(8),
      quoteVolume: BaseVolume.toFixed(8),`

**Comment by bmancini55** [comment]
Thanks for the report.  We will take a look and get a fix applied.

**Comment by bmancini55** [comment]
This is now released in https://github.com/altangent/ccxws/releases/tag/v0.29.4
