### ISSUE TITLE
Reconnecting does not work when there is a network issue

### ISSUE THREAD

**Issue by amitkukadia** [altangent/ccxws#117]
**Exchange**
Binance

**Subscription type**
trades

**Describe the bug**
The reconnection doesnt work when there is a network issue.(like turn off the wifi) Also no disconnected or closed event is fired

**To Reproduce**
run the following code and disconnect from internet and reconnect.

`const ccxws= require('ccxws')

const streamer = new ccxws.binance();

streamer.subscribeTrades({
    id: "BTCUSDT", // remote_id used by the exchange
    base: "BTC", // standardized base symbol for Bitcoin
    quote: "USDT", // standardized quote symbol for Tether
})

streamer.on("trade", trade => console.log(trade.price));
streamer.on("connecting", () => console.log('connecting'));
streamer.on("connected", () => console.log('connected'));
streamer.on("closed", () => console.log('closed'));
streamer.on("disconnected", () => console.log('disconnected'));`

**Expected behavior**
The disconnected event should be emited and reconnecting should be attempted.

**Additional context**
This might be the issue
[https://github.com/websockets/ws/issues/1158](https://github.com/websockets/ws/issues/1158)

**Comment by bmancini55** [comment]
Thanks for the info. I'll try to reproduce this locally and go from there.

**Comment by CodeHuggies** [comment]
Did you guys manage to solve this? Think I am encountering the same problem. 

Might be related to #130

**Comment by lejacobroy** [comment]
Same problem here with binance candles/trades, sockets get disconnected and don't reconnect multiple times per day.
