### ISSUE TITLE
Gate.io/KuCoin connection getting closed every few seconds

### ISSUE THREAD

**Issue by Dwynr** [altangent/ccxws#119]
**Exchange**
Gate.io / KuCoin

**Subscription type**
subscribeTrades (l2/l3 not tested)

**Describe the bug**
I'm trying to listen to all trade events on all markets for both Gate.io and KuCoin. Whenever I load the markets into the class using CCXT it just closes to connection after a second and tries to reconnect forever.

**To Reproduce**
1. Simply load all active markets from CCXT
2. Loop through them
3. Subscribe to each market using "subscribeTrades( { id, base, quote } )"
4. Gate.io will just connect/disconnect forever
5. KuCoin will connect to all markets and then disconnect again after like 5 seconds

**Expected behavior**
Sucessfully subscribe to all markets on both exchanges and listen for trade events.

**Versions**
Node: 10.17.0
CCXWS: 0.29.3

**Additional context**
I'm using the same method for almost every other exchange which works perfectly. Maybe I'm hitting some kind of request limit on both exchanges so they just close the socket on their side? I'm not sure if there is a limit on how much markets you can subscribe to at the same time. Would love to get this solved, I'm currently using a dirty script I made myself which connects to all exchanges and receives trade events (but the reconnect, lost connection etc. functions are not really that good), using CCXWS would be reaaaaaly handy! :)

**Comment by bmancini55** [comment]
Thanks for submitting an issue with great detail. 

In the past Gate.io had a limit of one market per socket. There were also limits on the number of socket connections that could be initiated. As a work around, we split markets across multiple machines/IPs. Looking through the Gate.io documentation, I'm not seeing this limit anymore. So it might be possible to simplify the client and get things working.

For KuCoin, it doesn't appear to have throttling around subscribing to markets which is often a cause of aborted connections.  We can make a change for this after confirming that it is indeed the issue.

**Comment by Dwynr** [comment]
My "dirty" script currently uses 100 markets per socket for KuCoin and connects to all markets in one socket for Gate.io, which seems to work. Maybe I can submit a PR if you can elaborate a bit more on how the client works (or is supposed to work). I already wrote a new client using BasicClient for Liquid (because that exchange was missing in CCXWS and I need it for my Project) so I kinda now the workflow. Would love to contribute to this great project!

**Comment by bmancini55** [comment]
The Gate.io client uses a multi-client since previously each socket only connected to a single market. The multi-socket client uses a single-socket client (BasicClient) under the hood.  So the change will be to get rid of the multi-client code, rename/promote the BasicClient to be the primary Gate.io client.  Then make the appropriate changes to the BasicClient to support the new multi-market functionality of Gate.io.  

If you want to take a stab at it, let me know. I was planning to look at it this afternoon or tomorrow and get it into the next release.  

The Liquid client you created would be something that would be a great PR if you are interested in sharing that code as well!

**Comment by Dwynr** [comment]
Yes I would love if you can take a look at both integrations and possible fix them! And yes of course I can share the Liquid integration, it only has the "subscribeTrades" function right now though. I will submit a PR as soon as I can.

**Comment by bmancini55** [comment]
This has been released in https://github.com/altangent/ccxws/releases/tag/v0.29.4

**Comment by bmancini55** [comment]
> @bmancini55 I don't know if the commits you pushed yesterday are final, but I see that Gate.io is working now. KuCoin now throws the 509 "exceeded max markets per session" error. I didn't want to create a new issue so I'll just ping you here. Thanks though for the quick fix.

@Dwynr the 509 "exceeded max markets per session" is a hard limit on the number of subscriptions that can be made per socket. The easiest work around is to instantiate the kucoin client for 100 markets at a time.

I added another issue to fix this more generally #125.

**Comment by Dwynr** [comment]
@bmancini55  Yea I thought you already integrated that in the latest release! My bad right there. I will follow the issue you linked and contribute whenever I can.
