### ISSUE TITLE
Removing Listeners

### ISSUE THREAD

**Issue by athenawisdoms** [altangent/ccxws#130]
After creating a `l2snapshot` listener for binance as shown,

```
const ccxws = require("ccxws");
const binance = new ccxws.binance();

const market = {id: "BTCUSDT",  base: "BTC",  quote: "USDT"};
binance.subscribeLevel2Snapshots(market);
binance.on("l2snapshot", snapshot => console.log(snapshot));
```

how do you stop listening to `l2snapshot` events without unsubscribing? 

Unsubscribing using `binance.unsubscribeLevel2Snapshots(market)` appears to reconnect to the same Wss URL but with different parameters, which sometimes causes what appear to be the exchange preventing quick reconnects:

 > Error: WebSocket was closed before the connection was established

**Comment by bmancini55** [comment]
If you want to remove a listener without unsubscribing you can use the `removeListener` method defined on all Node.js EventEmitter objects. https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener

An example would look like:

```javascript
const ccxws = require("ccxws");
const binance = new ccxws.binance();

const market = {id: "BTCUSDT",  base: "BTC",  quote: "USDT"};
binance.subscribeLevel2Snapshots(market);

binance.on("l2snapshot", snapshot => console.log('handler1', snapshot.sequenceId));

// create a function declaration, function expression, 
// or arrow function expression that can be referenced via removeListener
const handler2 = snapshot => console.log("handler2", snapshot.sequenceId);
binance.on("l2snapshot", handler2);

// remove the listener after 5 seconds
setTimeout(() => binance.removeListener("l2snapshot", handler2), 5000);
```

**Comment by athenawisdoms** [comment]
Thank you for the wonderful explanation!
