### ISSUE TITLE
De-dupe L2 Orderbook Data

### ISSUE THREAD

**Issue by CodeHuggies** [altangent/ccxws#131]
If I have 2 similar ccxws clients listening to a particular exchange's `l2update` event (for redundancy in case something happens) and saving them to a database/file, I think it is possible that the `l2update` data received by the 2 ccxws clients can have different `sequenceId` and `lastSequenceId`. 

In this situation, how do you de-dupe the `l2update` data? Do you suggest having a 3rd system read `l2update` streams from both ccxws clients and failing over from one client to the second client when a problem occurs with one of the client?

**Comment by bmancini55** [comment]
It will depend on the each exchange's usage of the sequence id whether separate socket connections will have the same sequence Id.  Some exchanges specify in their documentation that the id is per socket connection, per market, or resets periodically. Ultimately, the sequence id is meant to assist with detecting dropped messages, not necessarily providing a mechanism to de-dupe across multiple streams.  

De-duping multiple streams is beyond the scope of this library. But yes, in practice, having some arbiter that uses the best de-duping strategy possible for each exchange would be a good technique.  But, unless the exchange has set up global, monotonic, gapless sequenceId, you will likely still have some uncertainty.

**Comment by bmancini55** [comment]
Tagging as question and closing
