### ISSUE TITLE
HitBtc Client crashes when calling .close()

### ISSUE THREAD

**Issue by usmane3** [altangent/ccxws#133]
**Exchange**
HitBTC

**Subscription type**
Level2 orderbook updates

**Describe the bug**
The process crashes when calling .close() function. This is because the websocket might still be in the process of subscribing, but the close function sets the ws to null. 
The unsubscribe function also does not work for multiple markets in HitBTC client- it results in "too many requests" error.

**To Reproduce**
1. start HitBtc client
2. invoke the basicClient .close() function
3. Process will crash out with an uncaught exception

**Expected behavior**
Process should not crash out with an uncaught exception

**Additional context**

**Comment by bmancini55** [comment]
Thanks, reproduced with stacktrace:

```javascript
/ccxws/src/exchanges/hitbtc-client.js:33
      this._wss.send(
                ^
TypeError: Cannot read property 'send' of undefined
    at _sem.take (/ccxws/src/exchanges/hitbtc-client.js:33:17)
    at item.task (/ccxws/node_modules/semaphore/lib/semaphore.js:40:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
