### ISSUE TITLE
OKEX websocket throwing an ETIMEDOUT

### ISSUE THREAD

**Issue by usmane3** [altangent/ccxws#136]
**Exchange**
Okex

**Subscription type**
Level 2 orderbooks, trades.. 

**Describe the bug**
When trying to connect to wss://real.okex.com:10442/ws/v3 via the okex-client.js, we see an ETIMEDOUT.

**To Reproduce**
1. use okex-client.js
2. try and subscribe to l2updates for BTC USDT
3. You will see the error

**Expected behavior**
Should see l2updates

**Additional context**
Has okex changed the way one connects to their api?

**Comment by gmaf** [comment]
We experience same problems.
It seems they changed the port from `10442` to `8443` recently as they promised:
https://okexsupport.zendesk.com/hc/en-us/articles/360030824232-Change-in-V3-WebSocket-API-Address-Port-Number

**Comment by usmane3** [comment]
Ok thank you

**Comment by bmancini55** [comment]
Thanks for the report! Will get this fixed ASAP.  

It looks like that support ticket on OkEx was from 7 month, if you come across any other support notices that will cause outages, please submit a ticket so we can get a fix made prior to the outage date.

**Comment by bmancini55** [comment]
@gmaf thanks for the PR! 

Closed with release https://github.com/altangent/ccxws/releases/tag/v0.29.6
