### ISSUE TITLE
Concurrent zlib operations cause memory fragmentation

### ISSUE THREAD

**Issue by airking05** [altangent/ccxws#140]
**Exchange**
Huobi

**Subscription type**
Level2 orderbook updates

**Describe the bug**
I made 300 concurrency subscription with "Huobi Level2 orderbook updates" for a while(10min).
This has resulted in our docker containers crashing due to memory exhaustion.

**To Reproduce**
1. Make a large number of subscription in huobi
2. Wait for a while

It would be that crash is caused by "zlib".
There are some issues about "zlib" memory leak.
eg. [https://github.com/nodejs/node/issues/8871](url)

**Comment by bmancini55** [comment]
Thanks for submitting the issue!

Looks like as resolution for the `zlib` module they added better documentation: https://nodejs.org/docs/latest-v13.x/api/zlib.html#zlib_threadpool_usage_and_performance_considerations

Based on the documentation, under high load, the Huobi client code could cause memory fragmentation issues. Two possible solutions would be switching to the `unzipSync` or using a semaphore to restrict concurrent `zlib` operations. 

I can probably get to this sometime in the next week or two, but am also happy to accept a pull request in taking a stab at it.

**Comment by bmancini55** [comment]
A fix for this has been released in: https://github.com/altangent/ccxws/releases/tag/v0.31.1
