### ISSUE TITLE
Add exchange CEX.io

### ISSUE THREAD

**Issue by bmancini55** [altangent/ccxws#15]
**Exchange Name**
CEX.io

**Exchange API URL**
https://cex.io/websocket-api-dsl
wss://ws.cex.io/ws

**Describe the technology used by the exchange use for realtime updates?**
- Websockets - wss://ws.cex.io/ws
- Authenticated - requires an API token to access full Orderbook API

**Does each market require it own connection?**
No

**Describe how subscriptions occur**
Standard subscription payload as shown below. However, there are two modes for accessing data.  You can use the "Old Pair-Room Subscription" to access a partial order book, trades, and ticker.  You need to be authenticated to access the full order book subscription.
```
{
  "e": "subscribe",
  "rooms": [
    "pair-BTC-USD"
  ]
}
```

**Can you subscribe to tickers?**
Yes, each market has its own ticker feed
- It is part of the unified "room feed"

**Can you subscribe to candles?**
Yes
- There is a new public api that does not require authentication to access this feed

**Are trades and order book updates provided in a unified market feed?**
Yes

There is the "Old Pair-Room Subscription" as described here:
> This is the oldest subscription, on which Server is sending almost all public data to WebClient.

> The data, in fact, represents Order Book, Market Depth, Trade History and History Updates, 1d OHLCV updates. Therefore, the subscription is overlapping with new OHLCV subscriptions, Order Book subscription for authenticated user.

> Authenticated user can use either new, old or both.

There is also the authenticated order book feed that allow full depth snapshots and updates.

**Can you subscribe to trades?**
Yes, trades are broadcast as part of a unified market feed

**Can you subscribe to level2 snapshots?**
Yes, level2 snapshots are broadcast as part of an unified market feed - *however this is only a partial orderbook*
Yes, a level2 snapshot is broadcast at the start of level2 update subscription - *authentication required*

**Can you subscribe to level2 updates?**
Yes, there is a feed for level2 updates - *authentication required*

**Can you subscribe to level3 snapshots?**
No

**Can you subscribe to level3 updates?**
No

**Comment by bmancini55** [comment]
@jakebrown58, looking good.  

A couple suggestions for the BasicMultiClient implementation:   

* We can move the `subscribeLevel2Snapshots` and `unsubscribeLevel2Snapshot` methods https://github.com/altangent/ccxws/blob/c86018ae1b36e7afb736abeceb23f66abb2e501b/src/exchanges/cex-client.js#L23 into BasicMultiClient. Those methods should live there and were an oversight in the first implementation of BasicMultiClient.
* Ditto for the level2Snapshot related code in _subscribe https://github.com/altangent/ccxws/blob/c86018ae1b36e7afb736abeceb23f66abb2e501b/src/exchanges/cex-client.js#L40.  This should move into BasicMultiClient.
* Once the previous step is done, the only difference in the _subscribe method is the inclusion of the auth code during the construction of the BasicClient.  I think this can be solved by abstracting the construction of the basic client into a method that can be overridden in the implementation of BasicMultiClient.  So in BasicMultiClient._subscribe, https://github.com/altangent/ccxws/blob/c86018ae1b36e7afb736abeceb23f66abb2e501b/src/basic-multiclient.js#L73, will call a method _createBasicClient().  The implementations of BasicMultiClient implement that method return a constructed basic client that is used in the rest of the process of _subscribe.

**Comment by jakebrown58** [comment]
@bmancini55 excellent.  I had the same thoughts when I was writing that, but wanted to confirm with you on the unification before I spent time on it.  (And to make sure the update/snapshot stuff wasn't in there intentionally).
