### ISSUE TITLE
How to get all available markets?

### ISSUE THREAD

**Issue by nudabagana** [altangent/ccxws#158]
Hello, how do I get all available markets I can subscribe to? For example, I want btceur from all exchanges, some use "BTCEUR", some use "btceur", some use "BTC/EUR", there are even "XBTUSD". How do I find out, which market to use?

**Comment by bmancini55** [comment]
You can generate that list yourself manually or use a library like CCXT to provide markets for you.
The README has more information on the market structure: https://github.com/altangent/ccxws#market

**Comment by drsavant-pub** [comment]
Here's some sample code:
https://github.com/altangent/ccxws/issues/230
