### ISSUE TITLE
Add exchange Coinex

### ISSUE THREAD

**Issue by bmancini55** [altangent/ccxws#16]
**Exchange Name**
Coinex

**Exchange URL**
https://www.coinex.com/

**Exchange API URL**
Tickers - https://github.com/coinexcom/coinex_exchange_api/wiki/021ticker
Trades - https://github.com/coinexcom/coinex_exchange_api/wiki/045deals
L2 Snapshot - https://github.com/coinexcom/coinex_exchange_api/wiki/022depth

**Describe the technology used by the exchange use for realtime updates?**
- Documentation: https://github.com/coinexcom/coinex_exchange_api/wiki/041request_description
- Socket URL: wss://socket.coinex.com/
- Uses JSON RPC
- Uses Websockets

**Does each market require it own connection?**
Yes

**Describe how subscriptions occur**
```
#Request
{
  "method":"deals.subscribe",
  "params":[
    "BTCBCH"                        #1.market: See<API invocation description·market> 
  ],
  "id":16
}
```
It is standard JSON RPC subscribe. But it will unsubscribe if you subscribe to more than one feed per connection.

**Can you subscribe to tickers?**
Yes, each market has its own ticker feed
https://github.com/coinexcom/coinex_exchange_api/wiki/053state

**Can you subscribe to candles?**
Yes
https://github.com/coinexcom/coinex_exchange_api/wiki/046kline

**Are trades and order book updates provided in a unified market feed?**
No, it is 2 separate feeds
Market depth / orderbook - https://github.com/coinexcom/coinex_exchange_api/wiki/044depth
Transactions / trades / ticks/ match - https://github.com/coinexcom/coinex_exchange_api/wiki/045deals

**Can you subscribe to trades?**
Yes
https://github.com/coinexcom/coinex_exchange_api/wiki/045deals

**Can you subscribe to level2 snapshots?**
Yes, a level2 snapshot can be manually requested (Ex: Bittrex)
https://github.com/coinexcom/coinex_exchange_api/wiki/044depth

**Can you subscribe to level2 updates?**
Yes, there is a feed for level2 updates (Ex: Bitfinex)
https://github.com/coinexcom/coinex_exchange_api/wiki/044depth

**Can you subscribe to level3 snapshots?**
No

**Can you subscribe to level3 updates?**
No

**Comment by thiagofernando** [comment]
the websocket still working here?
