### ISSUE TITLE
Documentation table inaccuracy regarding Bitstamp level3Updates subscription.

### ISSUE THREAD

**Issue by greenman734** [altangent/ccxws#174]
**Exchange**
Bitstamp
**Subscription type**
level3Updates
**Describe the bug**
The table in the documentation that lists all the exchanges with their subscription capabilities is inaccurate with regard to 
Bitstamp's level3Updates capability: Their should not be a check-mark in the level3Updates column for Bitstamp as Bitstamp is not capable of subscribing to level3Updates. 

To confirm that this error exists, look at the bitstamp-client.js class (or its test class bitstamp-client.spec.js) to see that the hasLevel3Updates variable is not set to True.

**Comment by bmancini55** [comment]
Cool thanks!  This is probably left over from the v1 feed. 

It does look like they offer L3 data, but only as periodic snapshots not update streams, so either way the README needs to be updated.  I will create a separate issue for adding L3 snapshot support.
