### ISSUE TITLE
[QUESTION] how load markets by CCXWS

### ISSUE THREAD

**Issue by victor-trx** [altangent/ccxws#215]
In FAQ said: 
```
You can load markets in several ways:
...
Use CCXT to load markets
```

Sorry for stupid question but I can't find API to load market data by CCXWS library.

**Comment by bmancini55** [comment]
Hi, thanks for submitting your question, it's not a stupid question at all! CCXT is a separate library for making REST requests which takes efforts to standardize market symbols across exchanges.  This library only implements websocket support and does not include an API for fetching the markets from a REST endpoint at this time.
