### ISSUE TITLE
Add exchange Gate.io

### ISSUE THREAD

**Issue by rsbst23** [altangent/ccxws#24]
**Exchange URL**
https://www.gate.io/

**Exchange API URL**
Tickers - https://www.gate.io/docs/websocket/index.html?javascript#ticker-api
Trades - https://www.gate.io/docs/websocket/index.html?javascript#trade-api
L2 Snapshot - https://www.gate.io/docs/websocket/index.html?javascript#depth-api

**Describe the technology used by the exchange use for realtime updates?**
Documentation: https://www.gate.io/docs/websocket/index.html?javascript#
Socket URL: wss://ws.gate.io/v3/
Uses JSON RPC
Uses Websockets

Simple WebSocket test
```javascript
function socket_send_cmd(socket, cmd, params) {
    if (!params) 
    params = [];
    var msg = {
    id: client_id,
    method: cmd,    
    params: params
    };
    socket.send(JSON.stringify(msg));
}

var socket = new WebSocket('wss://ws.gate.io/v3');

socket.onopen = function () {
    console.log("Connected");
    socket_send_cmd(socket, 'trades.subscribe', ["ETH_USDT", "BTC_USDT"]);
};
socket.onmessage = function (e) {
    console.log('Server: ' + e.data);
}
```

---

Refer to [Contributing Guide](https://github.com/altangent/ccxws/blob/master/CONTRIBUTING.md) for additional information.

- Create client in `src/exchanges` that follows CCXWS library interface (refer to README)
- Create client test suite in `src/exchanges` to validate subscribe/unsubscribe methods and that data parsing is correct
- Add a lowercase export to `index.js`
- Implement subscribe to tickers sending logic
   - must support calling subscribe multiple times in a row with different markets
- Implement subscribe to trades
  - must support calling multiple times in a row with different markets
- Implement subscribe to orderbooks/depth
  - should default to highest limit and highest resolution interval
  - determine if exchange supports snapshots, updates, or both
  - if exchange supports broadcasting depth updates, CCXWS should initiate a snapshot request when subscribe for a market is called and broadcast a snapshot event

**Comment by OnlyC** [comment]
When I have a list of 3 markets, ccxws is subscribing to them and connected to them one by one:

`info: connected to wss://ws.gate.io/v3
info: subscribing to ticker Gateio btc_usdt
info: connected to wss://ws.gate.io/v3
info: subscribing to ticker Gateio eth_btc
info: connected to wss://ws.gate.io/v3
info: subscribing to ticker Gateio eth_usdt`

and when disconected/reconnect:

`warn: disconnected from wss://ws.gate.io/v3
warn: disconnected from wss://ws.gate.io/v3
warn: disconnected from wss://ws.gate.io/v3`

Is this normal behavior? Other exchanges is subscribing 3 times & connected 1 time.

**Comment by bmancini55** [comment]
Gate.io can only connect to a single market per socket.  We use the basic-multiclient to facilitate this functionality.  The net result is that you'll see one connect message per market.  In short, this is expected functionality.
