### ISSUE TITLE
Binance ticker subscribe to AllTickers & uses a lot of bandwidth

### ISSUE THREAD

**Issue by karimhossenbux** [altangent/ccxws#279]
I was making some test with Binance yesterday night.

I figure that when subscribing to Binance ticker for a single pair, it's still subscribing to AllTickers stream causing to use a lot bandwidth (400KB/s). 

And if I use 1 ticker per component, it multiply that value over and over (got it to 1200KB/s).

Here the library uses `!ticker@arr` which the stream for all markets:
https://github.com/altangent/ccxws/blob/d4b88a761f96d4b7e4c771693ca7db9772a886b4/src/exchanges/binance-base.js#L83-L93

Shouldn't it use `<symbol>@ticker` instead? to connect to a single market stream (the one we pass in param for example)

Binance doc: https://binance-docs.github.io/apidocs/spot/en/#individual-symbol-ticker-streams

**Comment by karimhossenbux** [comment]
fixed this in #280 👀

**Comment by bmancini55** [comment]
Released in https://github.com/altangent/ccxws/releases/tag/v0.44.0

Thanks!

**Comment by karimhossenbux** [comment]
Awesome, thank you for merging @bmancini55 🙏
