### ISSUE TITLE
Add exchange UpBit

### ISSUE THREAD

**Issue by bmancini55** [altangent/ccxws#40]
Please provide as much information as possible to make the addition of the exchange easier:

**Exchange API URL**
https://docs.upbit.com/docs/upbit-quotation-websocket

**Additional information about Websocket connection**
Documentation in Korean.  WebSocket supports Tickers, Trades, and L2 Orderbooks Updates (snapshot provided on connection).

BasicClient can probably be used, it looks like the socket allows subscribing to more than one feed per connection.

---

Refer to [Contributing Guide](https://github.com/altangent/ccxws/blob/master/CONTRIBUTING.md) for additional information.

- Create client in `src/exchanges` that follows CCXWS library interface (refer to README)
- Create client test suite in `src/exchanges` to validate subscribe/unsubscribe methods and that data parsing is correct
- Add a lowercase export to `index.js`
- Implement subscribe to tickers sending logic
   - must support calling subscribe multiple times in a row with different markets
- Implement subscribe to trades
  - must support calling multiple times in a row with different markets
- Implement subscribe to orderbooks/depth
  - should default to highest limit and smallest resolution interval
  - determine if exchange supports snapshots, updates, or both
  - if exchange supports broadcasting depth updates, CCXWS should initiate a snapshot request when subscribe for a market is called and broadcast a snapshot event

**Comment by OnlyC** [comment]
Please push update to npm. Thank you!

**Comment by bmancini55** [comment]
@OnlyC, will have a few updates (including this) this week. Thanks!
