### ISSUE TITLE
Add exchange Coinsuper

### ISSUE THREAD

**Issue by bmancini55** [altangent/ccxws#41]
**Exchange API URL**
https://github.com/coinsuperapi?tab=repositories

**Additional information about Websocket connection**
Looks to support Tickers, Trades, and L2 Updates (+Snapshot at start)

Requires using an API key to connect.

---

Refer to [Contributing Guide](https://github.com/altangent/ccxws/blob/master/CONTRIBUTING.md) for additional information.

- Create client in `src/exchanges` that follows CCXWS library interface (refer to README)
- Create client test suite in `src/exchanges` to validate subscribe/unsubscribe methods and that data parsing is correct
- Add a lowercase export to `index.js`
- Implement subscribe to tickers sending logic
   - must support calling subscribe multiple times in a row with different markets
- Implement subscribe to trades
  - must support calling multiple times in a row with different markets
- Implement subscribe to orderbooks/depth
  - should default to highest limit and highest resolution interval
  - determine if exchange supports snapshots, updates, or both
  - if exchange supports broadcasting depth updates, CCXWS should initiate a snapshot request when subscribe for a market is called and broadcast a snapshot event

**Comment by HalcyonLA** [comment]
@bmancini55 we are experiencing problems with connection to this service:

error: wss://apiwss.coinsuper.com:443 message=Unexpected server response: 404, stack=Error: Unexpected server response: 404
