### ISSUE TITLE
Bitmex -l2snapshot and l2update are missing symbol

### ISSUE THREAD

**Issue by usmankhanic** [altangent/ccxws#46]
**Exchange**
Bitmex

**Subscription type**
Level2 orderbook updates

**Describe the bug**
Bitmex uses the symbol to uniquely identify contracts  in the bitmex-client, lines 92 to 131, the symbol is used to set a market variable, but the symbol is ignored when creating the l2snapshot or l2update. This means that the term of the bitmex contract is ignored, as that resides in the symbol as opposed to inside the base and quote identifiers. 

We need the symbol to propagate through on the l2update and l2snapshot.

**To Reproduce**
Run the bitmex client
l2Update and l2snapshot do not have symbol

**Expected behavior**
l2update and l2snapshot should have symbol

**Additional context**

**Comment by usmankhanic** [comment]
Any luck with solving this?

**Comment by bmancini55** [comment]
Hi, thanks for submitting the issue! 

If you're interested in taking on the fix, it would be a huge help.  I'd like to get to this issue asap, but we're currently working through the backlog of existing pull requests.

**Comment by bmancini55** [comment]
This issue should be resolved now.  We also added automatic processing of the l2update price. 
More information: https://github.com/altangent/ccxws/releases/tag/0.21.0

**Comment by bmancini55** [comment]
@usmankhanic we released a new version that includes the market, from when `subscribe*` was called, in the result data as well. https://github.com/altangent/ccxws/releases/tag/v0.21.3
