### ISSUE TITLE
How to disconnected the socket!

### ISSUE THREAD

**Issue by bqtienhd** [altangent/ccxws#60]
I using client.close() but it's auto resconnected!

**Comment by bmancini55** [comment]
Which exchange(s) are you having difficulty with?

**Comment by bqtienhd** [comment]
I use Binance and Bittrex socket!

**Comment by bmancini55** [comment]
Looks like both of these clients need to clear out the reconnection timer when the user calls `close`.  Thanks!

**Comment by bqtienhd** [comment]
Tks you!. This is good library i need :D
