### ISSUE TITLE
CCXWS exchange disconnect / reconnect not working..

### ISSUE THREAD

**Issue by usmankhanic** [altangent/ccxws#63]
Notice the following error intermittently - but no auto reconnect after it occurs:

connecting to wss://stream.binance.com:9443/stream?streams=!ticker@arr
events.js:167
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: invalid status code 1005
....
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by bmancini55** [comment]
Hi, you may want to check this issue https://github.com/altangent/ccxws/issues/57.  The latest version of the 0.23.0 increases the Binance reconnect timeout to prevent churn.

**Comment by bmancini55** [comment]
If this issue is still unresolved after 0.23.0 then we can reopen the issue.

**Comment by usmankhanic** [comment]
Thx - we are still seeing disconnects
