### ISSUE TITLE
Bitfinex updates parsing error

### ISSUE THREAD

**Issue by pavel-khritonenko** [altangent/ccxws#64]
**Exchange**
Bitfinex

**Subscription type**
Level2 orderbook updates

**Describe the bug**
Library returns channel number as a price of the update (557880.00000000 price for BTC/USDT pair)

**Expected behavior**

**Additional context**

Bitfinex returns for updates `[ channel_id, price, count, amout ]`, and the current code parses it as: `let [price, count, size] = msg;`

**Comment by bmancini55** [comment]
@pavel-khritonenko thanks for the fix!  Version 0.23.1 has been created with this fix.
