### ISSUE TITLE
Binance ticker has timestamp in microseconds

### ISSUE THREAD

**Issue by aurecchia** [altangent/ccxws#72]
**Exchange**
Binance

**Subscription type**
Ticker

**Describe the bug**
The timestamp in the ticker message "is in microseconds", but should be in milliseconds according to the documentation. (all other exchanges report it in milliseconds).

**To Reproduce**
- Connect to ticker feed for Binance
- Receive a message?

**Expected behavior**
The timestamp should be in milliseconds. Looking at the code I can see that the value retrieved from the Binance feed is then multiplied by 1000 ([`src/exchanges/binance-client.js:239`](https://github.com/altangent/ccxws/blob/21a3953b287396d4b6b378b03a724d90a0d2366d/src/exchanges/binance-client.js#L239)). Was this done on purpose or is it maybe a leftover from a previous version of the Binance API?

I can raise a PR to fix this if you agree that the `* 1000` should be removed.

Cheers!

**Comment by bmancini55** [comment]
Thank you for submitting the issue. This is definitely a bug and looks like an oversight when the ticker function was implemented.  

A PR to remove the `* 1000` would be great!
