### ISSUE TITLE
okex / okex3 remote_id conflict

### ISSUE THREAD

**Issue by pavel-khritonenko** [altangent/ccxws#80]
**Exchange**
okex

**Subscription type**
Level2 orderbook updates

**Describe the bug**
Mismatch in exchanges id for `ccxt` and `ccxws`.

**To Reproduce**

We use `ccxt` for fetching markets list and `ccxws` to listen market data. If we get markets list from `ccxt` for okex and then we subscribe to Level2 updates in `ccxws` library - we get this error:
```
warn: failure response {"event":"error","message":"Channel spot/depth:eth_btc doesn't exist","errorCode":30040}
```

**Expected behavior**
Success subscription.

**Additional context**
In documentation `ETH-BTC` market mentioned, as we see `eth_btc` substituted in subscription.

`okex3` exchange class fetches correct data

**Comment by bmancini55** [comment]
Thanks! I created a broader scoped issue, #84, that will address the same issue across all exchanges.  Will merge your PR as part of that.
