### ISSUE TITLE
Bittrex: Error invoking Hub method 'corehub.QueryExchangeState' 

### ISSUE THREAD

**Issue by shimeilee** [altangent/ccxws#87]
**Exchange**
Bittrex

**Subscription type**
Trades, Level2 orderbook updates for BTC/LTC

**Describe the bug**
Received an error in invoking Hub method 'corehub.QueryExchangeState'. Might be a SignalR hub issue. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialise Bittrex Client
2. Call the function for subscribeLevel2Updates(market) with the specified market. 
3. Receive the following error. 

Error:
```
info: cloudflare connection to https://bittrex.com/
info: subscribing to level2 updates Bittrex BTCLTC
info: connected to wss://socket.bittrex.com/signalr
error: snapshot failed BTCLTC There was an error invoking Hub method 'corehub.QueryExchangeState'.
error: subscribe failed BTCLTC There was an error invoking Hub method 'corehub.SubscribeToExchangeDeltas'.
```

Here's the code snippet:
```
async subscribe(intent, uuid, full_instrument){
    this.bittrexClient = new ccxws.bittrex();

    let market = {
      id: "BTC-LTC",
      base: "LTC",
      quote: "BTC",
    };

    this.bittrexClient.subscribeLevel2Updates(market);
    this.bittrexClient.on("l2updates", snapshot => console.log(snapshot));
}

```

**Expected behavior**
Expected to receive and print JSON objects of the bids and asks price from Bittrex exchange to the console.

**Comment by bmancini55** [comment]
Thanks for submitting the issue!

I've seen this error when there is an invalid remote id.  For example BTC-ABY is a delisted market:

```javascript
let market = { id: "BTC-ABY", base: "ABY", quote: "BTC" };
let client = new ccxws.bittrex();
client.subscribeLevel2Updates(market);
client.on("l2update", console.log);
```

```
info: cloudflare connection to https://bittrex.com/
info: subscribing to level2 updates Bittrex BTC-ABY
info: connected to wss://socket.bittrex.com/signalr
error: snapshot failed BTC-ABY There was an error invoking Hub method 'corehub.QueryExchangeState'.
error: subscribe failed BTC-ABY There was an error invoking Hub method 'corehub.SubscribeToExchangeDeltas'.
```

From the error message you provided, if looks like it's receiving the remoteid `LTCBTC` instead of `LTC-BTC`.

```
info: cloudflare connection to https://bittrex.com/
info: subscribing to level2 updates Bittrex BTCLTC
info: connected to wss://socket.bittrex.com/signalr
error: snapshot failed BTCLTC There was an error invoking Hub method 'corehub.QueryExchangeState'.
error: subscribe failed BTCLTC There was an error invoking Hub method 'corehub.SubscribeToExchangeDeltas'.
```

Can you confirm that the market you used is actually
```
 let market = {
      id: "BTC-LTC",
      base: "LTC",
      quote: "BTC",
};
```

Thanks!

**Comment by shimeilee** [comment]
Hi Brian, you're right! The market id was wrong - I used the same market id format for Binance instead of Bittrex's. I managed to get the data when the id, base, and quote were amended to the correct format.

Thanks once again! :)
