### ISSUE TITLE
Trade "fullId" property is missing

### ISSUE THREAD

**Issue by evan-coygo** [altangent/ccxws#93]
v0.26.4

**Exchange**
Binance, Kraken, Coinbase Pro, Poloniex. This seems to be on every exchange but I haven't tried all of them

**Subscription type**
trades

**Describe the bug**
The "fullId" documented Trade event property is not included. This makes it difficult or impossible to know if the trade event is for the specific market you subscribed to if you've subscribed to multiple.

Here are a couple payloads received:
```js
 Trade {
      exchange: 'CoinbasePro',
      quote: 'ETH',
      base: 'BTC',
      tradeId: '8137331',
      unix: 1565828460948,
      side: 'buy',
      price: '0.01861000',
      amount: '0.02361238',
      buyOrderId: '1a8ff9efbf64423a92fa24f8c867ead0',
      sellOrderId: '9437194088d448a3af35aebb11584266' }
```
```js
{
      exchange: 'Binance',
      quote: 'ETH',
      base: 'BTC',
      tradeId: '126287492',
      unix: 1565828362478,
      side: 'buy',
      price: '0.01861000',
      amount: '0.10600000',
      buyOrderId: undefined,
      sellOrderId: undefined }
```

```js
 Trade {
      exchange: 'Kraken',
      quote: 'ETH',
      base: 'BTC',
      tradeId: '1565828233337300000',
      unix: 1565828233337,
      side: 'buy',
      price: '0.018590',
      amount: '13.50000000',
      buyOrderId: undefined,
      sellOrderId: undefined,
      rawUnix: '1565828233.337347' }
```
**To Reproduce**
```js
 this.ccxws.subscribeTrades(ccwxsMarket);
 this.ccxws.on('trade', (trade) => {
    console.log('---trade=', trade);
 });
```

**Expected behavior**
The [documented "fullId" property](https://github.com/altangent/ccxws#properties-2) should be on the event payload.

**Comment by bmancini55** [comment]
The second argument of all data events is the market that was used to subscribe to the feed:
```
this.ccxws.subscribeTrades(ccwxsMarket);
this.ccxws.on('trade', (trade, market) => {
    console.log('---trade=', trade, market);
 });
```

More info from the docs: https://github.com/altangent/ccxws#events

The `fullId` property is actually a deprecated property and should no longer be used. This is because the combination of exchange, base, and quote supplied in the data payload may be unique, but is not always. As a result, it's a better practice to look at the market provided in the second argument to determine the market the event is for.

**Comment by evan-coygo** [comment]
Got it, thanks. So the documentation just needs some updating. I can open a PR shortly.
