### ISSUE TITLE
Ability to provide custom wssPath for each client

### ISSUE THREAD

**Issue by thaaddeus** [altangent/ccxws#94]
Hi, I'd like to suggest an improvement about initializing clients with custom wssPaths/endpoints that I could create pull request for if you'd agree it makes sense. 
Currently there is no easy way (except changing `_wssPath`)  to change target wss Path when creating client and that might be useful for some use cases like connecting to testnet or replaying historical data via tardis-machine (like in this example: https://runkit.com/thad/tardis-machine-and-ccxws-example).
Would you be OK with pull request that would basically change each exchange constructor to something that would accept wssPath, but default one would be set to existing, eg:
```js
class BitmexClient extends BasicClient {
  constructor({wssPath: "wss://www.bitmex.com/realtime"}) {
```
?
Thanks!

**Comment by bmancini55** [comment]
Sure thing. As long as it's done in a backwards compatible way I don't see an issue with it at all.

**Comment by Tardis-Thad** [comment]
Thanks, I'll make the changes and send pull request this week then.

**Comment by backnight** [comment]
Hello guys !
Merry Christmas !

Any update on this?
