### ISSUE TITLE
BitMEX ticker support

### ISSUE THREAD

**Issue by evan-coygo** [altangent/ccxws#98]
BitMEX doesn't have a single subscription for full ticker data (last, ask, bid) but I believe we can combine two subscriptions to achieve it.

https://www.bitmex.com/app/wsAPI#Subscriptions

### ask & bid from "quote" subscription
The first is the "quote" subscription, which will give ask and bid rates from the "bidPrice" and "askPrice" properties.

example payload from `wss://www.bitmex.com/realtime?subscribe=quote:XBTUSD`
```json
{
  "timestamp":"2019-08-26T17:11:28.538Z",
  "symbol":"XBTUSD",
  "bidSize":773833,
  "bidPrice":10329.5,
  "askPrice":10330,
  "askSize":525732
},
```

### last from "trade" subscription
The second is the "trade" subscription, which can be used to get trades as they occur. The price of the most recent trade would be the "last" price from the "price" property.

example payload from `wss://www.bitmex.com/realtime?subscribe=trade:XBTUSD`
```json
{
  "timestamp":"2019-08-26T17:06:54.296Z",
 
 "symbol":"XBTUSD",
  "side":"Sell",
  "size":100,
  "price":10328.5,
  "tickDirection":"ZeroMinusTick",
  "trdMatchID":"b4d80cd6-7cf6-61f1-442a-8709f3108960",
  "grossValue":968200,
  "homeNotional":0.009682,
  "foreignNotional":100
}
```

### combining the two subscriptions
If keeping some data in memory in the client is acceptable, instead of just purely streaming event payloads as they come, then we could combine the two subscriptions and achieve a real-time ticker. 

To do so would require keeping three variables in memory, for "last", "ask", and "bid". 
* Whenever a new "quote" event comes in, we could store the "ask" and "bid" prices, use the most recent "last" price from memory (from the latest "trade" event), and send the payload down to the user of this lib.
* Whenever a new "trade" event comes in, we could store the "last" price from that trade, use the most recent "ask" and "bid" prices from memory (from the latest "quote" event), and send the payload down to the user of this lib.

We could probably also make a REST API call when the user first subscribes to get the last/ask/bid data immediately and send it down, to avoid the issue where it takes awhile for a trade event to occur after subscribing and they client is stuck waiting for the first "last" price point from the websocket.

`wss://www.bitmex.com/realtime?subscribe=trade,quote:XBTUSD`

**Comment by bmancini55** [comment]
I think it would be a great addition. If you don't mind putting together a PR that would be great!

We could also certainly add additional flags to the client. The test suite is already doing property based assertions for each class. 

```javascript
  ticker: {
    hasTimestamp: true,
    hasLast: true,
    hasOpen: true,
    hasHigh: true,
    hasLow: true,
    hasVolume: true,
    hasQuoteVolume: false,
    hasChange: true,
    hasChangePercent: true,
    hasBid: true,
    hasBidVolume: false,
    hasAsk: true,
    hasAskVolume: false,
  },
```

**Comment by bmancini55** [comment]
Have you looked at the `instrument` subscription?  Using it would simplify the logic into a single stream, plus data such as openInterest would be available.  It also sends the current status in the initial subscription (thought this would need to be filtered to markets that have a status of "Open".

```
let ws = new WebSocket('wss://www.bitmex.com/realtime?subscribe=instrument');
ws.onmessage = m => console.log(m.data);
```


It looks like after the initial status, fields are updated in separate messages:
```
{"table":"instrument","action":"update","data":[{"symbol":"XBTU19","openInterest":110054115,"openValue":1061251830945,"timestamp":"2019-09-09T22:00:20.000Z"}]}

{"table":"instrument","action":"update","data":[{"symbol":"XBTUSD","totalVolume":1664781673431,"volume":285686,"totalTurnover":23917830452777830,"turnover":2777098556,"timestamp":"2019-09-09T22:00:21.518Z"}]}

{"table":"instrument","action":"update","data":[{"symbol":"XBTUSD","lastPrice":10289.5,"lastTickDirection":"MinusTick","lastChangePcnt":-0.0136,"timestamp":"2019-09-09T22:00:28.830Z"}]}

{"table":"instrument","action":"update","data":[{"symbol":"XBTUSD","lastPriceProtected":10289.5,"bidPrice":10289.5,"midPrice":10289.75,"askPrice":10290,"impactBidPrice":10289.1244,"impactMidPrice":10290.25,"impactAskPrice":10291.2422,"timestamp":"2019-09-09T22:00:28.830Z"}]}
```

**Comment by evan-coygo** [comment]
interesting, I saw it mentioned but didn't see any sample data so I didn't expect it to have that much information. I can try taking a stab at that

**Comment by bmancini55** [comment]
I didn't know what it did either till I played around with BitMEX today while getting a better understanding of the changes in your PR.  

It looks like it will require a bit of bookkeeping as well.  But the code should be simpler than the two feeds approach.

**Comment by evan-coygo** [comment]
I'm finally getting around to taking a look today. The instrument API is barely documented so it's hard to know exactly what I'm looking for but from what I can tell it may not be enough to get last, ask, and bid data alone (the minimum I'm looking for in a ticker).


I've filtered out only messages related to XBTUSD, below are what I'm seeing. I see a last price and a bid price (impactBid) but nothing about ask. I'm guessing the message isn't sent until it gets changed. So if instrument channel is the way you wanna go we might need to make a REST call first to get the initial bid/ask, then store when its updated. What do you think @bmancini55 ?

```json
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       openValue: 9197752889982,
       fairPrice: 8773.99,
       markPrice: 8773.99,
       indicativeSettlePrice: 8773.2,
       timestamp: '2019-11-12T20:49:50.293Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       openInterest: 807033500,
       openValue: 9197760799500,
       timestamp: '2019-11-12T20:49:52.791Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       totalVolume: 1818218310429,
       volume: 75626597,
       totalTurnover: 25653689063793430,
       turnover: 860791558621,
       timestamp: '2019-11-12T20:49:53.077Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       impactBidPrice: 8777.3194,
       impactMidPrice: 8777.75,
       timestamp: '2019-11-12T20:49:53.077Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       lastPrice: 8777,
       lastChangePcnt: 0.0066,
       timestamp: '2019-11-12T20:49:54.883Z' } ] }
ignoring  .BLTCXBT
ignoring  .BXBT
ignoring  .BXBT_NEXT
ignoring  .BXRPXBT_NEXT
ignoring  .XBT
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       lastPrice: 8776.5,
       lastChangePcnt: 0.0065,
       timestamp: '2019-11-12T20:49:55.070Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       lastPrice: 8776,
       timestamp: '2019-11-12T20:49:55.172Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       lastPriceProtected: 8777.3194,
       openValue: 9195339699000,
       fairPrice: 8776.68,
       markPrice: 8776.68,
       indicativeSettlePrice: 8775.89,
       timestamp: '2019-11-12T20:49:55.172Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       lastPrice: 8775.5,
       lastChangePcnt: 0.0064,
       timestamp: '2019-11-12T20:49:55.942Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       lastPrice: 8775,
       timestamp: '2019-11-12T20:49:56.067Z' } ] }
{ table: 'instrument',
  action: 'update',
  data: 
   [ { symbol: 'XBTUSD',
       openInterest: 807084317,
       openValue: 9195918707898,
       timestamp: '2019-11-12T20:49:57.695Z' } ] }
^C
```

**Comment by bmancini55** [comment]
Released in https://github.com/altangent/ccxws/releases/tag/v0.33.0
