### ISSUE TITLE
Bittrex tries to access this._subCount when sub/unsub but its undefined, throws error

### ISSUE THREAD

**Issue by evan-coygo** [altangent/ccxws#99]
ccxws v 0.27.2

**Exchange**
Bittrex

**Subscription type**
level2 orderbook updates

**Describe the bug**
It looks like the Bittrex client is trying to access the internal `this._subCount` property but it's `undefined` (perhaps it needs to be bound for the correct `this`). 

```
Bittrex ccxws websocket error: No Hub
Cannot read property 'BTC-EOS' of undefined
    at BittrexClient._sendSub (/home/evan/devel/coygo/webapp/.meteor/desktop-build/node_modules/ccxws/src/exchanges/bittrex-client.js:126:48)
    at BittrexClient._subscribe (/home/evan/devel/coygo/webapp/.meteor/desktop-build/node_modules/ccxws/src/exchanges/bittrex-client.js:108:14)
    at BittrexClient.subscribeLevel2Updates (/home/evan/devel/coygo/webapp/.meteor/desktop-build/node_modules/ccxws/src/exchanges/bittrex-client.js:82:10)
    at classDefinition.(anonymous function).registerOrderBookListener (/home/evan/devel/coygo/webapp/.meteor/desktop-build/desktop.asar/trading/exchange-clients/ExchangeClientCcxtCcxwsCommon.js:177:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

TypeError: Cannot read property 'BTC-EOS' of undefined
    at BittrexClient._sendUnsub (/home/evan/devel/coygo/webapp/.meteor/desktop-build/node_modules/ccxws/src/exchanges/bittrex-client.js:150:20)
    at BittrexClient._unsubscribe (/home/evan/devel/coygo/webapp/.meteor/desktop-build/node_modules/ccxws/src/exchanges/bittrex-client.js:119:14)
    at BittrexClient.unsubscribeLevel2Updates (/home/evan/devel/coygo/webapp/.meteor/desktop-build/node_modules/ccxws/src/exchanges/bittrex-client.js:90:10)
    at classDefinition.(anonymous function).deregisterOrderBookListener (/home/evan/devel/coygo/webapp/.meteor/desktop-build/desktop.asar/trading/exchange-clients/ExchangeClientCcxtCcxwsCommon.js:363:16)
(node:10161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

The problem lines are:
```js
 _sendSub(remote_id) {
    // increment market counter
    this._subCount[remote_id] = (this._subCount[remote_id] || 0) + 1;
```
```js
_sendUnsub(remote_id) {
    // decrement market count
    this._subCount[remote_id] -= 1;
  }
```

**To Reproduce**
Subscribe to l2 updates on Bittrex BTC-EOS market.

This happened once but I can't reproduce it since then, so I just grabbed the logs to place them here in hopes that it's enough details.

**Expected behavior**
Connection is successful and doesn't throw error.

**Additional context**

**Comment by benoist** [comment]
I see only _resetSubCount() instantiates the this._subCount but this method is never called.

I can confirm the socket works when you manually call the function

```javascript
const socket = new ccxws.bittrex()
socket._resetSubCount()
socket.subscribeLevel2Snapshots(market)
```

**Comment by benoist** [comment]
I see it also gets called after the connected message is emitted

```javascript
 _onConnected() {
    clearTimeout(this._reconnectHandle);
    this.emit("connected");
    this._subCount = {};
    this._tickerConnected = false;
    this._watcher.start();
    for (let marketSymbol of this._tickerSubs.keys()) {
      this._sendSubTickers(marketSymbol);
    }
    for (let marketSymbol of this._tradeSubs.keys()) {
      this._sendSub(marketSymbol);
    }
    for (let marketSymbol of this._level2UpdateSubs.keys()) {
      this._sendSub(marketSymbol);
    }
  }
```

However if you subscribe to the on("connected") this function will be called before the subCount is instantiated.

Should the emit("connected") not be called last or later?

**Comment by evan-coygo** [comment]
I'm not sure I understand ccxws's internals enough to confidently fix this. can anyone else pick this up? I'm seeing fairly regular connection issues because of this

**Comment by bmancini55** [comment]
I'll get the change above into a new release tomorrow which may resolve the issue for you. 

Do you have any other debug info? And/or could you provide a code snippet of attached events for the client?  Specifically do you have any logic around the `connected` event?

**Comment by evan-coygo** [comment]
I still can't reproduce this consistently but in the code where it happens sometimes, I have no logic waiting for the `connected`, I just create the client, subscribe to l2 updates, and register a callback on the event

```js

this.ccxws = new ccxws.bittrex({
  reconnectIntervalMs: 15 * 60 * 1000
});
this.ccxws.subscribeTicker(ccwxsMarket);
this.ccxws.subscribeLevel2Updates(ccwxsMarket);

this.ccxws.on('ticker', async (data, market) => {
  // do something
});
this.ccxws.on('l2snapshot', async (data, market) => {
  // do something
});

this.ccxws.on('l2update', async (data, market) => {
  // do something
});
```

**Comment by bmancini55** [comment]
Two fixes are now available in release v0.27.3:

1. Reordered connection logic to match logic in other clients
2. Fixed a race condition on subscribe. 

Most likely the second is the culprit of your issues. The calls to subscribe were checking for the existence of the websocket variable `_wss` https://github.com/altangent/ccxws/blob/22eafc7fc5330a7fac75be7cf62a4602a390f7c0/src/exchanges/bittrex-client.js#L118 to determine if it is ok to immediately send a subscription to the server.  

`_wss` is created in `_connect` https://github.com/altangent/ccxws/blob/22eafc7fc5330a7fac75be7cf62a4602a390f7c0/src/exchanges/bittrex-client.js#L191

However, `_subCount` does not get set until a valid connection is established with the handler `_onConnected`. 

This opened a window where a subscription would think the websocket was open when it was not actually open yet and when the call stack `subscribeLevel2Update` > `_subscribe` > `_sendSub` > occurred without actually be connected it would abend.  

A new flag has been added `_isConnected` that gets set when the connection handler `_onConnected` is fired and is unset when disconnected event is fired in `_onDisconnected`.  This flag is now checked in the subscribe method to determine if an immediate subscription can be performed.

I'm going to close this issue for now, if you're still seeing the issue after this fix then we can reopen it.

**Comment by evan-coygo** [comment]
@bmancini55 it looks like the release got built and tagged but is not yet published on npm. once it's available I'll try it out and let you know if I still run into issues. thanks for the quick fix!

**Comment by bmancini55** [comment]
@evan-coygo v0.27.3 should be live on NPM now
